# Generated by Django 3.2 on 2021-04-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='product name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.TextField(verbose_name='detail')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='registered date')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'product',
            },
        ),
    ]
