# Generated by Django 3.2 on 2021-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210409_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
